package com.quantitymeasurement.entity;


import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/*
 * =========================================================
 * User Entity
 * =========================================================
 *
 * Purpose:
 * Represents application users for authentication & authorization.
 *
 * Stored in database table: users
 *
 * Fields:
 * - id        : Primary Key
 * - username  : Unique login identifier
 * - password  : Encrypted password (BCrypt)
 * - role      : User role (ROLE_USER / ROLE_ADMIN)
 *
 * Used in:
 * - Authentication (login)
 * - JWT token generation
 * - Spring Security (UserDetailsService)
 */

@Entity   // Marks this class as a JPA Entity (DB table)
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = "password") // avoid printing password in logs
public class User {

    /*
     * PRIMARY KEY
     *
     * id:
     * - Unique identifier for each user
     * - Auto-generated by database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * USERNAME
     *
     * - Used for login
     * - Must be unique
     */
    @Column(nullable = false, unique = true)
    private String username;

    /*
     * PASSWORD
     *
     * - Stored in ENCRYPTED form (BCrypt)
     * - Never stored as plain text
     */
    @Column(nullable = false)
    private String password;

    /*
     * ROLE
     *
     * - Defines user permissions
     *
     * Examples:
     * ROLE_USER
     * ROLE_ADMIN
     */
    @Column(nullable = false)
    private String role;
}